name: Build and Publish DLLs

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  run_dlls_builder:
    runs-on: windows-latest

    steps:
      - name: Use External Action
        uses: OSTOLEX-Technologies/DLL-builder-action@3df1e827a7525477efd01cee12fa806740ee904e
        with:
          token: ${{ secrets.GH_PAT_PACK }}
